import { expect,test } from '@playwright/test';
import { resetLocalE2eAccount } from '../helpers/local-e2e'; import { appRuntimeUrl } from '../setup/app-runtime';

test('Become practice survives sign-out, returns, reviews, and closes',async({page},testInfo)=>{
 const email=`practice-${testInfo.project.name}@rts.test`,password='local-e2e-only-password';await resetLocalE2eAccount(email);
 try{
  await page.goto(appRuntimeUrl('/sign-up'));await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);await Promise.all([page.waitForURL(/dashboard$/),page.getByRole('button',{name:'Create account'}).click()]);
  await page.goto(appRuntimeUrl('/formation/awaken.pay-attention.observe'));await page.getByLabel('What happened?').fill('The meeting ended early.');await page.getByLabel('What happened inside me?').fill('I felt dismissed.');await page.getByLabel('What did you notice in your body?').fill('Tight shoulders.');await page.getByRole('button',{name:'Save and continue'}).click();
  await page.getByRole('button',{name:'Reflect with AI'}).click();await page.getByLabel('What would you like to save in your own words?').fill('I expected not to be heard.');await page.getByRole('button',{name:'Save my added insight'}).click();await page.getByRole('link',{name:'Continue'}).click();
  await page.getByLabel('What is the observable fact?').fill('The meeting ended early.');await page.getByLabel('What is my interpretation?').fill('My contribution was unwanted.');await page.getByRole('radio',{name:'expectation'}).check();await page.locator('textarea[name="belief_expectation_text"]').fill('I expect dismissal.');await page.getByRole('button',{name:'Save and continue'}).click();await page.getByRole('link',{name:'Continue'}).click();
  await page.getByLabel('What outcome am I trying to control?').fill('Everyone approving my idea.');await page.getByLabel('What is actually true in the present moment?').fill('The meeting ended; I do not know why.');await page.getByLabel('What is the next right step?').fill('Ask one clear question.');await page.getByRole('button',{name:'Save as open practice'}).click();
  await expect(page.getByText('waiting for real life')).toBeVisible();await page.getByRole('button',{name:'Sign out'}).click();await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);await Promise.all([page.waitForURL(/dashboard$/),page.getByRole('button',{name:'Sign in'}).click()]);
  await expect(page.getByRole('link',{name:'Resume'})).toHaveAttribute('href','/formation/become.practice.return');await page.getByRole('link',{name:'Return to this practice'}).click();
  await page.getByLabel(/What happened/).fill('I asked and learned the agenda was shortened.');await page.getByRole('button',{name:'Save what happened'}).click();await page.getByLabel('Your reflection').fill('I can ask before assuming.');await page.getByRole('button',{name:'Save review'}).click();await page.getByRole('button',{name:'Close practice'}).click();
  await expect(page.getByRole('link',{name:'Return to this practice'})).toHaveCount(0);await expect(page.getByRole('link',{name:'Resume'})).toBeVisible();
  await page.getByRole('link',{name:'View formation history'}).click();await expect(page).toHaveURL(/\/history$/);await expect(page.getByRole('heading',{name:'Your words and what they formed'})).toBeVisible();await expect(page.getByText('User wording').first()).toBeVisible();await expect(page.getByText('Structured by you').first()).toBeVisible();await expect(page.getByText('The meeting ended early.').first()).toBeVisible();await expect(page.getByText(/curriculum progress/i)).toHaveCount(0);
 }finally{await resetLocalE2eAccount(email)}
});
