import pg from 'pg';
import { expect,test } from '@playwright/test';
import { resetLocalE2eAccount } from '../helpers/local-e2e';
import { appRuntimeUrl } from '../setup/app-runtime';

test('user explicitly grants, uses, saves, and revokes one prior entry',async({page},testInfo)=>{const email=`selected-context-${testInfo.project.name}@rts.test`,password='local-e2e-only-password';await resetLocalE2eAccount(email);const pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL});try{
 await page.goto(appRuntimeUrl('/sign-up'));await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);await Promise.all([page.waitForURL(/dashboard$/),page.getByRole('button',{name:'Create account'}).click()]);
 const user=(await pool.query('select id from auth.users where email=$1',[email])).rows[0].id;
 const prior=(await pool.query(`insert into public.journal_entries(user_id,curriculum_version_id,node_id,entry_kind,body) values($1,'phase-1-v1','awaken.pay-attention.observe','event','The earlier meeting ended suddenly.') returning id`,[user])).rows[0].id;
 const entries=[];for(const [node,kind,body] of [['become.control','control_target','control'],['become.receive','present_truth','truth'],['become.next-step','next_right_step','step'],['become.practice.return','practice_outcome','outcome'],['become.practice.review','practice_review','I asked before assuming.']] as const)entries.push((await pool.query(`insert into public.journal_entries(user_id,curriculum_version_id,node_id,entry_kind,body) values($1,'phase-1-v1',$2,$3,$4) returning id`,[user,node,kind,body])).rows[0].id);
 const practice=(await pool.query(`insert into public.practices(user_id,curriculum_version_id,node_id,control_target_entry_id,present_truth_entry_id,next_right_step_entry_id,state,opened_at,reviewed_at) values($1,'phase-1-v1','become.practice.open',$2,$3,$4,'reviewed',now(),now()) returning id`,[user,entries[0],entries[1],entries[2]])).rows[0].id;await pool.query(`insert into public.practice_returns(user_id,practice_id,outcome_entry_id,review_entry_id,reviewed_at) values($1,$2,$3,$4,now())`,[user,practice,entries[3],entries[4]]);
 await page.goto(appRuntimeUrl(`/practices/${practice}`));await expect(page.getByText('The earlier meeting ended suddenly.')).toBeVisible();await page.getByRole('button',{name:'Allow this entry'}).click();await expect(page.getByRole('button',{name:'Revoke permission'})).toBeVisible();await page.getByRole('button',{name:'Reflect with AI'}).click();await expect(page.getByText('What did you notice just before your body responded?')).toBeVisible();await page.getByRole('button',{name:'Save AI suggestion'}).click();await expect.poll(async()=>Number((await pool.query('select count(*) from public.ai_artifacts where user_id=$1',[user])).rows[0].count)).toBe(1);await page.getByRole('button',{name:'Revoke permission'}).click();await expect(page.getByRole('button',{name:'Allow this entry'})).toBeVisible();expect(await pool.query('select revoked_at is not null revoked from public.ai_context_grants where user_id=$1 and journal_entry_id=$2',[user,prior])).toMatchObject({rows:[{revoked:true}]});
 }finally{await pool.end();await resetLocalE2eAccount(email)}});
