import { randomUUID } from 'node:crypto';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { createTestPool,withAuthenticatedActor } from '../helpers/db'; import { practiceRepository } from '../../server/data/practice-repository'; import { closePractice,createPractice,recordPracticeReturn,reviewPractice } from '../../server/services/practice-service';
const pool=createTestPool();const actorId=randomUUID();const actorClient={auth:{getUser:async()=>({data:{user:{id:actorId,email:null}},error:null})}};const repository=practiceRepository({pool});
beforeAll(async()=>{await pool.query(`insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,'',now(),'{}','{}',now(),now())`,[actorId,`${actorId}@rts.test`]);await pool.query("insert into public.user_curriculum_state(user_id,curriculum_version_id,current_node_id,state) values($1,'phase-1-v1','bridge.see-clearly-become','in_progress')",[actorId])});
afterAll(async()=>{await pool.query('delete from auth.users where id=$1',[actorId]);await pool.end()});
describe('practice lifecycle',()=>{
 it('persists exact plan wording, identity-only lineage, and an independent curriculum resume',async()=>{const sourceJournal=await pool.query("insert into public.journal_entries(user_id,curriculum_version_id,node_id,entry_kind,body) values($1,'phase-1-v1','see-clearly.belief-expectation','belief_expectation','belief') returning id",[actorId]);const sourceRecord=await pool.query("insert into public.formation_records(user_id,curriculum_version_id,node_id,record_type,value_text,source_journal_entry_id,provenance) values($1,'phase-1-v1','see-clearly.belief-expectation','belief','belief',$2,'user_authored') returning id",[actorId,sourceJournal.rows[0].id]);const practice=await createPractice({controlTargetText:'  control  ',presentTruthText:'truth',nextRightStepText:'step'},{repository,actorClient});expect(practice).toMatchObject({state:'waiting_for_real_life',lockVersion:0});const stored=await repository.get(actorId,practice.id);expect(stored).toMatchObject({controlTargetText:'  control  ',presentTruthText:'truth',nextRightStepText:'step'});const state=await pool.query('select current_node_id from public.user_curriculum_state where user_id=$1',[actorId]);expect(state.rows[0].current_node_id).toBe('become.practice.return');const link=await pool.query("select source_formation_record_id,target_practice_id from public.formation_links where user_id=$1 and link_type='see_clearly_to_become'",[actorId]);expect(link.rows).toEqual([{source_formation_record_id:sourceRecord.rows[0].id,target_practice_id:practice.id}])});
 it('allows exactly one concurrent return, leaves one exact outcome, and advances resume',async()=>{const practice=await repository.getUnfinished(actorId);expect(practice).not.toBeNull();const attempts=await Promise.allSettled(['first outcome','second outcome'].map(outcomeText=>recordPracticeReturn({practiceId:practice!.id,expectedLockVersion:0,outcomeText},{repository,actorClient})));expect(attempts.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(attempts.filter(x=>x.status==='rejected')).toHaveLength(1);const stored=await repository.get(actorId,practice!.id);expect(['first outcome','second outcome']).toContain(stored?.outcomeText);expect(stored).toMatchObject({state:'ready_to_review',lockVersion:1});const state=await pool.query('select current_node_id,state::text from public.user_curriculum_state where user_id=$1',[actorId]);expect(state.rows).toEqual([{current_node_id:'become.practice.review',state:'in_progress'}])});
 it('rejects malformed direct lineage and completes on the approved terminal node',async()=>{const practice=await repository.getUnfinished(actorId);expect(practice).not.toBeNull();const wrongJournal=await pool.query("insert into public.journal_entries(user_id,curriculum_version_id,node_id,entry_kind,body) values($1,'phase-1-v1','become.next-step','next_right_step','wrong') returning id",[actorId]);await expect(withAuthenticatedActor(pool,actorId,client=>client.query("insert into public.formation_links(user_id,link_type,source_practice_id,target_journal_entry_id) values($1,'practice_to_return',$2,$3)",[actorId,practice!.id,wrongJournal.rows[0].id]))).rejects.toMatchObject({code:'23514'});const wrongRecord=await pool.query("insert into public.formation_records(user_id,curriculum_version_id,node_id,record_type,value_text,source_journal_entry_id,provenance) values($1,'phase-1-v1','become.next-step','next_right_step','wrong',$2,'user_authored') returning id",[actorId,wrongJournal.rows[0].id]);await expect(withAuthenticatedActor(pool,actorId,client=>client.query("insert into public.formation_links(user_id,link_type,source_formation_record_id,target_practice_id) values($1,'see_clearly_to_become',$2,$3)",[actorId,wrongRecord.rows[0].id,practice!.id]))).rejects.toMatchObject({code:'23514'});const review=await reviewPractice({practiceId:practice!.id,expectedLockVersion:1,reviewText:'exact review'},{repository,actorClient});expect(review.state).toBe('reviewed');await closePractice({practiceId:practice!.id,expectedLockVersion:2},{repository,actorClient});const state=await pool.query('select current_node_id,state::text from public.user_curriculum_state where user_id=$1',[actorId]);expect(state.rows).toEqual([{current_node_id:'become.practice.review',state:'completed'}])});
});
