import { createHash } from 'node:crypto';
import { REFLECT_VERSIONS } from '../ai/context-builder';
import { configuredAiProvider, type AiProvider } from '../ai/openai-adapter';
import { runReflect } from '../ai/orchestrator';
import { requireActor } from '../auth/require-actor';
import { aiContextGrantRepository, type AiContextGrantRepository } from '../data/ai-context-grant-repository';

type ActorClient=Parameters<typeof requireActor>[0];
type Dependencies=Readonly<{repository?:AiContextGrantRepository;actorClient?:ActorClient;provider?:AiProvider;now?:()=>number}>;
function required(value:unknown,label:string):asserts value is string{if(typeof value!=='string'||!value.trim())throw new Error(`${label} is required.`)}
function uuid(value:unknown,label:string):asserts value is string{required(value,label);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new Error(`${label} must be a UUID.`)}
export function practiceReflectFingerprint(currentEntryId:string,priorEntryId:string,grantId:string,grantRevision:number){return createHash('sha256').update(JSON.stringify({mode:'reflect',stage:'become',node:'awaken.pay-attention.reflect',currentEntryId,priorEntryId,grantId,grantRevision,...REFLECT_VERSIONS})).digest('hex')}
export async function grantPriorEntryPermission(input:{journalEntryId:string},dependencies:Dependencies={}){uuid(input.journalEntryId,'journal entry');const actor=await requireActor(dependencies.actorClient,input);return(dependencies.repository??aiContextGrantRepository()).grant({actorId:actor.id,journalEntryId:input.journalEntryId})}
export async function revokePriorEntryPermission(input:{grantId:string;expectedRevision:number},dependencies:Dependencies={}){uuid(input.grantId,'grant');if(!Number.isInteger(input.expectedRevision)||input.expectedRevision<1)throw new Error('expected revision is required.');const actor=await requireActor(dependencies.actorClient,input);return(dependencies.repository??aiContextGrantRepository()).revoke({actorId:actor.id,...input})}
export async function getPriorEntryPermission(practiceId:string,dependencies:Dependencies={}){uuid(practiceId,'practice');const actor=await requireActor(dependencies.actorClient);return(dependencies.repository??aiContextGrantRepository()).findForPractice(actor.id,practiceId)}
export async function reflectOnPracticeReview(input:{intentId:string;currentEntryId:string;priorEntryId:string;grantId:string;grantRevision:number},dependencies:Dependencies={}){uuid(input.intentId,'intentId');uuid(input.currentEntryId,'current entry');uuid(input.priorEntryId,'prior entry');uuid(input.grantId,'grant');if(!Number.isInteger(input.grantRevision)||input.grantRevision<1)throw new Error('grant revision is required.');const actor=await requireActor(dependencies.actorClient,input);const repository=dependencies.repository??aiContextGrantRepository();const reservation=await repository.reserve({actorId:actor.id,...input,requestFingerprint:practiceReflectFingerprint(input.currentEntryId,input.priorEntryId,input.grantId,input.grantRevision),...REFLECT_VERSIONS});if(reservation.kind!=='dispatch')return reservation;const now=dependencies.now??Date.now;const started=now();const result=await runReflect(reservation.context,dependencies.provider??configuredAiProvider());await repository.complete({actorId:actor.id,threadId:reservation.threadId,status:result.kind,durationMs:Math.max(0,now()-started),output:result.kind==='success'?result.value:null});return{...result,threadId:reservation.threadId}}
export async function savePracticeReflectSuggestion(input:{threadId:string;questions:readonly string[]},dependencies:Dependencies={}){uuid(input.threadId,'thread');if(!Array.isArray(input.questions)||input.questions.length<1||input.questions.some(question=>typeof question!=='string'||!question.trim()))throw new Error('questions are required.');const actor=await requireActor(dependencies.actorClient,input);return(dependencies.repository??aiContextGrantRepository()).saveSuggestion({actorId:actor.id,threadId:input.threadId,content:{questions:input.questions}})}
